# Generated by Django 4.2.2 on 2024-09-18 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                blank=True, to="mailing_service.client", verbose_name="client"
            ),
        ),
    ]
