# Generated by Django 4.2.2 on 2024-09-29 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0002_alter_mailing_clients"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_change_status", "Can change mailing status"),
                    ("can_block_clients", "Can block clients"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AddField(
            model_name="client",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="is_blocked"),
        ),
    ]
