# Generated by Django 4.2.2 on 2024-09-29 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0003_alter_mailing_options_client_is_blocked"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("deactivate_mailing", "Can deactivate mailing"),
                    ("view_all_mailings", "Can view all mailings"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
