# Generated by Django 4.2.2 on 2024-09-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок блога",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Введите текст блога", verbose_name="body"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Загрузите аватар блога",
                        null=True,
                        upload_to="image/pictures",
                        verbose_name="image",
                    ),
                ),
                (
                    "publish_at",
                    models.DateField(blank=True, null=True, verbose_name="created_at"),
                ),
                (
                    "view_counter",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Счетчик просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "блог",
                "verbose_name_plural": "блоги",
                "ordering": ["title"],
            },
        ),
    ]
